# #
# # JDBC properties
# #
# spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
# spring.datasource.username=springstudent
# spring.datasource.password=springstudent

# #! Spring Security Credentials
# spring.security.user.name=user
# spring.security.user.password=asd

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/employee_directory
        username: springstudent
        password: springstudent
    security:
        user:
            name: user
            password: asd

logging:
    level:
        org:
            springframework:
                security: DEBUG